import type { Metadata } from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import ResponsiveNav from "./components/Navigation/ResponsiveNav";
import Footer from "./components/Footer/footer";

const poppins = Poppins({ 
  weight:['400','700'],
  subsets:['latin']
 });

export const metadata: Metadata = {
  title: "Text Inbox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ResponsiveNav/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
